### ISSUE TITLE
Sniff output for the Japanese K65 RGB

### ISSUE THREAD

**Issue by manvari** [ZirconiumX/corsair-re#4]
Per your [request](https://github.com/mattanger/ckb-next/issues/286#issuecomment-364821539). Here's the content of the extracted output.tgz archive: it contained one single text file named `1b17.txt`.

[1b17.txt](https://github.com/ZirconiumX/corsair-re/files/1715960/1b17.txt)

**Comment by Ravenslofty** [comment]
Thank you very much!

Added in 00dd2316.
